### PR TITLE
A proposed ice marginal lake variable description

### PR DESCRIPTION
**Pull request by PennyHow**
Here is a proposed variable description for an ice marginal lake. 

I noticed that there is usually a reference to a WMO variable from the OSCAR database. I removed this from here as ice marginal lake is not defined there.

### CODE REVIEW

**Review by open-science-data — COMMENTED** [review]
I see that you could not find this specific variable in OSCAR database. We are in fact in some cases using also this GCMD Keywords database as a reference. I have checked that, but I think: 'íce marginal lake' definition is not provided there either. Could you however provide a link to some reference to that description of this specific variable? To have our entries harmonized we need this 'via' link to description to be present in the variable entry, as this is required then in validation process.

**Comment by PennyHow** [comment]
I've been scouring the internet all morning for a definition in a database and cannot find one. I think the most suitable definition I can find is [Glacial Lake Extent](https://gcmd.earthdata.nasa.gov/KeywordViewer/scheme/Earth%20Science?gtm_search=lake&gtm_scheme=Earth%20Science) as an ice marginal lake is a type of glacial lake.

But I know you already are using this definition [here](https://github.com/ESA-EarthCODE/open-science-catalog-metadata/blob/main/variables/glacial-lake-extent/catalog.json).

Can you also use it for ice marginal lake? If not, then I think the definition you already have for [glacial lake extent](https://github.com/ESA-EarthCODE/open-science-catalog-metadata/blob/main/variables/glacial-lake-extent/catalog.json) can be used instead of creating one for "ice marginal lake".

**Comment by edobrowolska** [comment]
Hi Penny, Apologies for getting back to you that late, I have updated then the description of the product with the variable: Glacial lake extent, and I would suggest to keep this one as neither myself I was trying to find a definition of ice margin lake variable, but could not find any reference. Maybe to not repeat twice the same variable, I would then keep the Glacial lake extent, and then keep the ice marginal lake as a keyword in the product description, so it will be findable by users. Please let me know if that could work and if yes I will close this PR.

**Comment by PennyHow** [comment]
I think this is a fine solution, so I am happy for you to close this PR. Thanks!

**Pull request closed without merging**
